### ISSUE TITLE
Fix error when filtering in Denite

### ISSUE THREAD

**Issue by eikendev** [eikendev/dotfiles#7]
Sometimes the following message is thrown. I believe this is triggered when there are many candidates to filter.

```
[denite] Traceback (most recent call last):
[denite]   File "/home/user/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/rplugin.py", line 65, in do_map
[denite]     return do_map(ui, args[1], args[2])
[denite]   File "/home/user/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/map.py", line 20, in do_map
[denite]     return MAPPINGS[name](denite, params)
[denite]   File "/home/user/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/map.py", line 95, in _filter_async
[denite]     denite._update_candidates()
[denite]   File "/home/user/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 465, in _update_candidates
[denite]     self._update_displayed_texts()
[denite]   File "/home/user/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 512, in _update_displayed_texts
[denite]     for i in range(0, candidates_len)
[denite]   File "/home/user/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 512, in <listcomp>
[denite]     for i in range(0, candidates_len)
[denite]   File "/home/user/.local/share/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 632, in _get_candidate_display_text
[denite]     candidate = self._candidates[index]
[denite] IndexError: list index out of range
[denite] Please execute :messages command.
```

**Comment by eikendev** [comment]
Denite is to be replaced as a whole.
